alias gaa="git add -A"
alias gcm="git commit -m"
alias gpr="git pull --rebase origin master"
alias gpfwlo="git push --force-with-lease origin"
alias t="bin/rails test"
alias t-all="TEST_ALL_FEATURES=1 bin/rails test"
alias ngrok-start="tmp/ngrok http -subdomain=ghdev-jshorty -host-header=rewrite 127.0.0.1"
alias cs-server="export GH_HOSTNAME=\"ghdev-jshorty.ngrok.io\"; bin/server"
